[workspace]
resolver = "1"

members = [
    "nfs3",
    "rpc_protocol",
    "tests/alloc",
    "tests/no_alloc",
    "tests/zcopy",
    "xdr_codegen",
    "xdr_lib",
    "benches/zcopy",
    "benches/serialize",
]

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
